#!/bin/bash

echo "🎛️ EURORACK.GRID Firebase Setup"
echo "================================"
echo ""
echo "This will help you set up Firebase for user auth and module ownership tracking."
echo ""
echo "📝 STEP 1: Create Firebase Project"
echo "1. Open: https://console.firebase.google.com"
echo "2. Click 'Create Project'"
echo "3. Name it: eurorack-grid"
echo "4. Disable Google Analytics (not needed)"
echo "5. Click 'Create Project'"
echo ""
read -p "Press ENTER when you've created the project..."

echo ""
echo "🔐 STEP 2: Enable Authentication"
echo "1. In Firebase Console → Authentication (left sidebar)"
echo "2. Click 'Get Started'"
echo "3. Click 'Email/Password' → Enable → Save"
echo "4. (Optional) Click 'Google' → Enable → Save"
echo ""
read -p "Press ENTER when authentication is enabled..."

echo ""
echo "📊 STEP 3: Create Firestore Database"
echo "1. In Firebase Console → Firestore Database (left sidebar)"
echo "2. Click 'Create Database'"
echo "3. Choose 'Start in test mode'"
echo "4. Select your region (closest to you)"
echo "5. Click 'Enable'"
echo ""
read -p "Press ENTER when Firestore is created..."

echo ""
echo "🔑 STEP 4: Get Your Config"
echo "1. Click the gear ⚙️ → Project Settings"
echo "2. Scroll down to 'Your apps'"
echo "3. Click the </> (Web) button"
echo "4. App nickname: eurorack-web"
echo "5. Click 'Register app'"
echo "6. Copy the entire firebaseConfig object"
echo ""
echo "It looks like this:"
echo "const firebaseConfig = {"
echo "  apiKey: \"...\","
echo "  authDomain: \"...\","
echo "  projectId: \"...\","
echo "  storageBucket: \"...\","
echo "  messagingSenderId: \"...\","
echo "  appId: \"...\""
echo "};"
echo ""
read -p "Press ENTER when you've copied your config..."

echo ""
echo "📝 STEP 5: Add Config to firebase-config.js"
echo "1. Open firebase-config.js in this folder"
echo "2. Replace the placeholder config with your real one"
echo "3. Save the file"
echo ""
read -p "Press ENTER when you've added your config..."

echo ""
echo "✅ Setup Complete!"
echo ""
echo "To test the Firebase connection:"
echo "1. Run: npm start (or python3 -m http.server 8000)"
echo "2. Open: http://localhost:8000"
echo "3. Try creating an account and buying a module!"
echo ""
echo "The test environment will show:"
echo "- Login/signup working"
echo "- Module purchases with jamnutz"
echo "- Owned modules in inventory (static)"
echo "- Drag to rack to animate!"
echo ""
echo "Once this works, we'll integrate it into your real site!"